# Generated by Django 4.1.6 on 2023-02-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="email",
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="entry",
            name="file",
            field=models.FileField(null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="entry",
            name="grade",
            field=models.CharField(
                choices=[("9", "9"), ("10", "10"), ("11", "11"), ("12", "12")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="school",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="entry",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
