# Generated by Django 4.1.6 on 2023-03-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0002_entry_email_entry_file_entry_grade_entry_school_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="file",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
