# Generated by Django 4.1.6 on 2023-03-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0003_alter_entry_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="file",
            field=models.FileField(null=True, upload_to="static"),
        ),
    ]
